"""
Normalisation des noms de pays
EN → FR pour cohérence
"""

# Villes connues : ville (lowercase) → pays en français
# Utilisé pour corriger les offres (ODDO BHF, Deloitte, etc.) où le pays manque ou est erroné
CITY_TO_COUNTRY = {
    # France (villes courantes pour ODDO BHF et autres sources sans pays)
    'paris': 'France',
    'lyon': 'France',
    'clichy': 'France',
    'marseille': 'France',
    'toulouse': 'France',
    'bordeaux': 'France',
    'lille': 'France',
    'nice': 'France',
    'nantes': 'France',
    'strasbourg': 'France',
    'rennes': 'France',
    'montpellier': 'France',
    'saint-denis': 'France',
    'reims': 'France',
    'le havre': 'France',
    'saint-étienne': 'France',
    'toulon': 'France',
    'grenoble': 'France',
    'dijon': 'France',
    'angers': 'France',
    'nîmes': 'France',
    'villeurbanne': 'France',
    'aix-en-provence': 'France',
    'nanterre': 'France',
    'courbevoie': 'France',
    'levallois-perret': 'France',
    'neuilly-sur-seine': 'France',
    'puteaux': 'France',
    'la défense': 'France',
    'suresnes': 'France',
    # Tunisie
    'tunis': 'Tunisie',
    # Afrique subsaharienne
    'douala': 'Cameroun',
    'yaoundé': 'Cameroun',
    'yaounde': 'Cameroun',
    'lubumbashi': 'République Démocratique du Congo',
    'kinshasa': 'République Démocratique du Congo',
    'libreville': 'Gabon',
    'port-gentil': 'Gabon',
    'cotonou': 'Bénin',
    'abidjan': "Côte d'Ivoire",
    'dakar': 'Sénégal',
    'bamako': 'Mali',
    'ouagadougou': 'Burkina Faso',
    'niamey': 'Niger',
    'lomé': 'Togo',
    'lome': 'Togo',
    'accra': 'Ghana',
    'lagos': 'Nigeria',
    'abuja': 'Nigeria',
    'casablanca': 'Maroc',
    'rabat': 'Maroc',
    'marrakech': 'Maroc',
    'alger': 'Algérie',
    'oran': 'Algérie',
    'cairo': 'Égypte',
    'le caire': 'Égypte',
    'johannesburg': 'Afrique du Sud',
    'le cap': 'Afrique du Sud',
    'cape town': 'Afrique du Sud',
    # Autres villes internationales courantes
    'londres': 'Royaume-Uni',
    'london': 'Royaume-Uni',
    'dublin': 'Irlande',
    'amsterdam': 'Pays-Bas',
    'bruxelles': 'Belgique',
    'brussels': 'Belgique',
    'brussel': 'Belgique',
    'luxembourg': 'Luxembourg',
    'saint-pierre-port': 'Guernesey',
    'genève': 'Suisse',
    'geneve': 'Suisse',
    'zurich': 'Suisse',
    'madrid': 'Espagne',
    'barcelone': 'Espagne',
    'barcelona': 'Espagne',
    'rome': 'Italie',
    'roma': 'Italie',
    'milan': 'Italie',
    'milano': 'Italie',
    'berlin': 'Allemagne',
    'munich': 'Allemagne',
    'francfort': 'Allemagne',
    'frankfurt': 'Allemagne',
    'vienne': 'Autriche',
    'vienna': 'Autriche',
    'lisbonne': 'Portugal',
    'lisbon': 'Portugal',
    'varsovie': 'Pologne',
    'warsaw': 'Pologne',
    'prague': 'République Tchèque',
    'budapest': 'Hongrie',
    'bucarest': 'Roumanie',
    'bucharest': 'Roumanie',
    'moscou': 'Russie',
    'moscow': 'Russie',
    'istanbul': 'Turquie',
    'athènes': 'Grèce',
    'athens': 'Grèce',
    'new york': 'États-Unis',
    'los angeles': 'États-Unis',
    'chicago': 'États-Unis',
    'san francisco': 'États-Unis',
    'montréal': 'Canada',
    'montreal': 'Canada',
    'toronto': 'Canada',
    'quebec': 'Canada',
    'québec': 'Canada',
    'vancouver': 'Canada',
    'singapour': 'Singapour',
    'singapore': 'Singapour',
    'hong kong': 'Hong-Kong',
    'hong-kong': 'Hong-Kong',
    'tokyo': 'Japon',
    'jakarta': 'Indonésie',
    'djibouti': 'Djibouti',
    'sydney': 'Australie',
    'melbourne': 'Australie',
    'dubaï': 'Émirats Arabes Unis',
    'dubai': 'Émirats Arabes Unis',
    'abu dhabi': 'Émirats Arabes Unis',
    'bombay': 'Inde',
    'mumbai': 'Inde',
    'bangalore': 'Inde',
    'delhi': 'Inde',
    'chennai': 'Inde',
    'shanghai': 'Chine',
    'pékin': 'Chine',
    'pekin': 'Chine',
    'beijing': 'Chine',
    'séoul': 'Corée du Sud',
    'seoul': 'Corée du Sud',
    'tel aviv': 'Israël',
    'riyadh': 'Arabie Saoudite',
    'doha': 'Qatar',
    'nassau': 'Bahamas',
    'panama city': 'Panama',
    'panama': 'Panama',
    'kuwait city': 'Koweït',
    'kuwait': 'Koweït',
    'lima': 'Pérou',
    'kuala lumpur': 'Malaisie',
    'bangkok': 'Thaïlande',
    'hanoï': 'Vietnam',
    'hanoi': 'Vietnam',
    'ha noi': 'Vietnam',
    'ho chi minh': 'Vietnam',
    'ho chi minh city': 'Vietnam',
    'saigon': 'Vietnam',
    # Philippines
    'taguig': 'Philippines',
    'makati': 'Philippines',
    'makati city': 'Philippines',
    'manila': 'Philippines',
    'manille': 'Philippines',
    'cebu': 'Philippines',
    'quezon city': 'Philippines',
    # Pologne
    'katowice': 'Pologne',
    'warszawa': 'Pologne',
    'wrocław': 'Pologne',
    'wroclaw': 'Pologne',
    'kraków': 'Pologne',
    'krakow': 'Pologne',
    'łódź': 'Pologne',
    'lodz': 'Pologne',
    'gdańsk': 'Pologne',
    'gdansk': 'Pologne',
    'poznań': 'Pologne',
    'poznan': 'Pologne',
    # Belgique
    'diegem': 'Belgique',
    'zaventem': 'Belgique',
    'gand': 'Belgique',
    'ghent': 'Belgique',
    'anvers': 'Belgique',
    'antwerp': 'Belgique',
    'liège': 'Belgique',
    'liege': 'Belgique',
    'namur': 'Belgique',
    'louvain': 'Belgique',
    'leuven': 'Belgique',
    'wavre': 'Belgique',
    # Allemagne
    'eschborn': 'Allemagne',
    'frankfurt am main': 'Allemagne',
    'frankfurt am main ': 'Allemagne',
    'düsseldorf': 'Allemagne',
    'dusseldorf': 'Allemagne',
    'hambourg': 'Allemagne',
    'hamburg': 'Allemagne',
    'cologne': 'Allemagne',
    'köln': 'Allemagne',
    'koln': 'Allemagne',
    'Stuttgart': 'Allemagne',
    'stuttgart': 'Allemagne',
    'nuremberg': 'Allemagne',
    'nürnberg': 'Allemagne',
    'leipzig': 'Allemagne',
    'dresde': 'Allemagne',
    'dresden': 'Allemagne',
    'hannover': 'Allemagne',
    'hanovre': 'Allemagne',
    # Argentine
    'caba': 'Argentine',
    'buenos aires': 'Argentine',
    'córdoba': 'Argentine',
    'rosario': 'Argentine',
    # Uruguay
    'montevideo': 'Uruguay',
    # Mexique
    'ciudad de méxico': 'Mexique',
    'ciudad de mexico': 'Mexique',
    'mexico city': 'Mexique',
    'guadalajara': 'Mexique',
    'monterrey': 'Mexique',
    # Irlande
    'dublin 2': 'Irlande',
    'dublin 4': 'Irlande',
    'cork': 'Irlande',
    'galway': 'Irlande',
    # Suisse
    'grand-lancy': 'Suisse',
    'grand lancy': 'Suisse',
    'bâle': 'Suisse',
    'basel': 'Suisse',
    'berne': 'Suisse',
    'bern': 'Suisse',
    'lausanne': 'Suisse',
    # Jordanie
    'amman': 'Jordanie',
    # Chypre
    'nicosie': 'Chypre',
    'nicosia': 'Chypre',
    'limassol': 'Chypre',
    # Lituanie
    'vilnius': 'Lituanie',
    'kaunas': 'Lituanie',
    # Lettonie
    'riga': 'Lettonie',
    # Taïwan
    'taipei city': 'Taïwan',
    'taipei': 'Taïwan',
    '台北市': 'Taïwan',
    'hsinchu': 'Taïwan',
    'taichung': 'Taïwan',
    'tainan': 'Taïwan',
    # Malaisie
    'penang': 'Malaisie',
    'kuching': 'Malaisie',
    'iskandar puteri': 'Malaisie',
    'johor bahru': 'Malaisie',
    'petaling jaya': 'Malaisie',
    # Malte
    'msida': 'Malte',
    'sliema': 'Malte',
    'valletta': 'Malte',
    'la valette': 'Malte',
    # Île Maurice
    'ebene': 'Île Maurice',
    'port louis': 'Île Maurice',
    # Pakistan
    'karachi': 'Pakistan',
    'lahore': 'Pakistan',
    'islamabad': 'Pakistan',
    # Sri Lanka
    'colombo': 'Sri Lanka',
    # Corée du Sud
    'youngdeungpo-gu': 'Corée du Sud',
    'youngdeungpo': 'Corée du Sud',
    'busan': 'Corée du Sud',
    # Danemark
    'frederiksberg': 'Danemark',
    'copenhague': 'Danemark',
    'copenhagen': 'Danemark',
    # Espagne
    'malaga': 'Espagne',
    'málaga': 'Espagne',
    'valencia': 'Espagne',
    'séville': 'Espagne',
    'seville': 'Espagne',
    'bilbao': 'Espagne',
    'palma': 'Espagne',
    'las palmas': 'Espagne',
    'zaragoza': 'Espagne',
    # Arabie Saoudite
    'alkhobar': 'Arabie Saoudite',
    'al khobar': 'Arabie Saoudite',
    'jeddah': 'Arabie Saoudite',
    'riyad': 'Arabie Saoudite',
    'riyadh': 'Arabie Saoudite',
    # Îles Caïmans
    'camana bay': 'Îles Caïmans',
    'george town': 'Îles Caïmans',
    # Bermudes
    'bermuda': 'Bermudes',
    'hamilton': 'Bermudes',
    # Colombie
    'bogotá': 'Colombie',
    'bogota': 'Colombie',
    'medellín': 'Colombie',
    'medellin': 'Colombie',
    # Pérou
    'lima': 'Pérou',
    # Chili
    'santiago': 'Chili',
    # Nouvelle-Zélande
    'auckland': 'Nouvelle-Zélande',
    'wellington': 'Nouvelle-Zélande',
    # Europe centrale/orientale
    'kyiv': 'Ukraine',
    'kiev': 'Ukraine',
    'zagreb': 'Croatie',
    'ljubljana': 'Slovénie',
    'belgrade': 'Serbie',
    'beograd': 'Serbie',
    'bratislava': 'Slovaquie',
    'tallinn': 'Estonie',
    'helsinki': 'Finlande',
    'oslo': 'Norvège',
    'stockholm': 'Suède',
    'copenhague': 'Danemark',
    'copenhagen': 'Danemark',
    'frederiksberg': 'Danemark',
    'debrecen': 'Hongrie',
    'pécs': 'Hongrie',
    'pecs': 'Hongrie',
    'sofia': 'Bulgarie',
    'athènes': 'Grèce',
    'athens': 'Grèce',
    'baku': 'Azerbaïdjan',
    'tblisi': 'Géorgie',
    'tbilisi': 'Géorgie',
    'minsk': 'Biélorussie',
    'chisinau': 'Moldavie',
    'reykjavik': 'Islande',
    # Amérique latine
    'caracas': 'Venezuela',
    'bogotá': 'Colombie',
    'bogota': 'Colombie',
    'quito': 'Équateur',
    'oranjestad': 'Aruba',
    'curaçao': 'Curaçao',
    'curacao': 'Curaçao',
    'san josé': 'Costa Rica',
    'san jose': 'Costa Rica',
    'miguel hidalgo': 'Mexique',
    'guadalajara': 'Mexique',
    'monterrey': 'Mexique',
    # Inde (villes supplémentaires)
    'ahmedabad': 'Inde',
    'kolkata': 'Inde',
    'calcutta': 'Inde',
    'pune': 'Inde',
    'bengaluru': 'Inde',
    'new delhi': 'Inde',
    'new delhi': 'Inde',
    'hyderabad': 'Inde',
    'gurugram': 'Inde',
    'gurgaon': 'Inde',
    'noida': 'Inde',
    # Australie
    'adelaide': 'Australie',
    'perth': 'Australie',
    'brisbane': 'Australie',
    'canberra': 'Australie',
    # Japon
    'chiyoda': 'Japon',
    'osaka': 'Japon',
    'nagoya': 'Japon',
    'fukuoka': 'Japon',
    'sapporo': 'Japon',
    # Hong Kong districts
    'quarry': 'Hong-Kong',
    'quarry bay': 'Hong-Kong',
    'kwun tong': 'Hong-Kong',
    'kowloon': 'Hong-Kong',
    'central': 'Hong-Kong',
    # Koweït
    'koweït': 'Koweït',
    'koweit': 'Koweït',
    'kuwait': 'Koweït',
    # France (villes supplémentaires)
    'gradignan': 'France',
    'mannheim': 'Allemagne',
    'freeport': 'Bahamas',
    'wan chai': 'Hong-Kong',
    'wanchai': 'Hong-Kong',
    'padova': 'Italie',
    'padoue': 'Italie',
    'venise': 'Italie',
    'venice': 'Italie',
    'florence': 'Italie',
    'firenze': 'Italie',
    'bari': 'Italie',
    'bologne': 'Italie',
    'bologna': 'Italie',
    'naples': 'Italie',
    'napoli': 'Italie',
    'palerme': 'Italie',
    'palermo': 'Italie',
    'torino': 'Italie',
    'turin': 'Italie',
    'lisboa': 'Portugal',
    'porto': 'Portugal',
    'kota kinabalu': 'Malaisie',
    'renens': 'Suisse',
    'la coruña': 'Espagne',
    'la coruna': 'Espagne',
    'la corunna': 'Espagne',
    'corunna': 'Espagne',
    'managua': 'Nicaragua',
    'linz': 'Autriche',
    'graz': 'Autriche',
    'salzburg': 'Autriche',
    'salzburg': 'Autriche',
    'antwerpen': 'Belgique',
    'antwerp': 'Belgique',
    'suzhou': 'Chine',
    'chengdu': 'Chine',
    'shenzhen': 'Chine',
    'guangzhou': 'Chine',
    'tianjin': 'Chine',
    'chongqing': 'Chine',
    'hangzhou': 'Chine',
    'wuhan': 'Chine',
    'nanjing': 'Chine',
    'xi\'an': 'Chine',
    'qingdao': 'Chine',
    # Taïwan (chinois traditionnel)
    '台南市': 'Taïwan',
    '新竹市': 'Taïwan',
    '台中市': 'Taïwan',
    '高雄市': 'Taïwan',
    '台北市': 'Taïwan',
    '桃園市': 'Taïwan',
    # Hong Kong districts
    'kwun tong': 'Hong-Kong',
    'pau': 'France',
    'rouen': 'France',
    'metz': 'France',
    'caen': 'France',
    'orléans': 'France',
    'amiens': 'France',
    'clermont-ferrand': 'France',
    'tours': 'France',
    'saint-nazaire': 'France',
    'mulhouse': 'France',
    'béziers': 'France',
    'limoges': 'France',
    'perpignan': 'France',
    'poitiers': 'France',
    'brest': 'France',
    'bordeaux': 'France',
    # Belgique (région)
    'flanders': 'Belgique',
    'flandre': 'Belgique',
    'wallonie': 'Belgique',
    # Afrique
    'luanda': 'Angola',
    'nairobi': 'Kenya',
    'lusaka': 'Zambie',
    'harare': 'Zimbabwe',
    'dar es salaam': 'Tanzanie',
    'accra': 'Ghana',
    'addis abeba': 'Éthiopie',
    'addis ababa': 'Éthiopie',
    'manila': 'Philippines',
    'issy-les-moulineaux': 'France',
    'issy les moulineaux': 'France',
    'lille cedex': 'France',
    'saint-cloud': 'France',
    'boulogne-billancourt': 'France',
    'vincennes': 'France',
    'massy': 'France',
    'vélizy': 'France',
    'velizy': 'France',
    'sophia antipolis': 'France',
    'fontainebleau': 'France',
    'chartres': 'France',
    'tours': 'France',
    'montpellier': 'France',
    'blagnac': 'France',
    'montoir-de-bretagne': 'France',
    'montoir de bretagne': 'France',
    # Brésil
    'são paulo': 'Brésil',
    'sao paulo': 'Brésil',
    'recife': 'Brésil',
    'barueri': 'Brésil',
    'nova lima': 'Brésil',
    'brasilia': 'Brésil',
    'belo horizonte': 'Brésil',
    'rio de janeiro': 'Brésil',
    # États-Unis (villes supplémentaires)
    'charlotte': 'États-Unis',
    'atlanta': 'États-Unis',
    'houston': 'États-Unis',
    'boston': 'États-Unis',
    'seattle': 'États-Unis',
    'philadelphia': 'États-Unis',
    'philadelphie': 'États-Unis',
    'dallas': 'États-Unis',
    'miami': 'États-Unis',
    'denver': 'États-Unis',
    'minneapolis': 'États-Unis',
    'tampa': 'États-Unis',
    'san antonio': 'États-Unis',
    'arlington': 'États-Unis',
    'brooklyn': 'États-Unis',
    'morristown': 'États-Unis',
    # Canada (villes supplémentaires)
    'calgary': 'Canada',
    'ottawa': 'Canada',
    'mississauga': 'Canada',
    # Roumanie
    'cluj-napoca': 'Roumanie',
    'cluj napoca': 'Roumanie',
    'timișoara': 'Roumanie',
    'timisoara': 'Roumanie',
    'iași': 'Roumanie',
    'iasi': 'Roumanie',
    # Royaume-Uni (villes supplémentaires)
    'leeds': 'Royaume-Uni',
    'glasgow': 'Royaume-Uni',
    'birmingham': 'Royaume-Uni',
    'manchester': 'Royaume-Uni',
    'edinburgh': 'Royaume-Uni',
    'édimbourg': 'Royaume-Uni',
    'bristol': 'Royaume-Uni',
    'newcastle': 'Royaume-Uni',
    'cheltenham': 'Royaume-Uni',
    'portsmouth': 'Royaume-Uni',
    # Inde (villes supplémentaires)
    'navi mumbai': 'Inde',
    'jaipur': 'Inde',
    'coimbatore': 'Inde',
    'nagpur': 'Inde',
    'indore': 'Inde',
    'bhubaneswar': 'Inde',
    # Indonésie
    'semarang': 'Indonésie',
    # Philippines
    'mandaluyong': 'Philippines',
    'muntinlupa': 'Philippines',
    # Vietnam
    'ho chiminh': 'Vietnam',
    'hô-chi-minh-ville': 'Vietnam',
    # Chine
    'dalian': 'Chine',
    # Portugal (villes supplémentaires)
    'braga': 'Portugal',
    'aveiro': 'Aveiro',
    'matosinhos': 'Portugal',
    # Costa Rica
    'heredia': 'Costa Rica',
    # Australie
    'ballarat': 'Australie',
    # Scandinavie
    'stavanger': 'Norvège',
    'trondheim': 'Norvège',
    # Slovaquie
    'bratislava': 'Slovaquie',
    # Bulgarie
    'sofia': 'Bulgarie',
    # Croatie
    'zagreb': 'Croatie',
    # Île Maurice
    'ebène': 'Île Maurice',
    # Singapour (nom français)
    'singapour': 'Singapour',
    # Hong Kong
    'hong-kong': 'Hong-Kong',
    # Allemagne — villes supplémentaires
    'kronberg': 'Allemagne',
    'kronberg im taunus': 'Allemagne',
    'eschborn': 'Allemagne',
    # Costa Rica
    'belén': 'Costa Rica',
    'belen': 'Costa Rica',
    'san josé': 'Costa Rica',
    # Colombie
    'barranquilla': 'Colombie',
    # Malaisie (région)
    'selangor': 'Malaisie',
    # Émirats
    'abou dabi': 'Émirats Arabes Unis',
    'al sila tower': 'Émirats Arabes Unis',
    'sowwah square': 'Émirats Arabes Unis',
    # Villes EY/Accenture manquantes
    'prague 1 - nove mesto': 'République Tchèque',
    'prague 1': 'République Tchèque',
    'freiburg i. br.': 'Allemagne',
    'freiburg': 'Allemagne',
    'hsinchu city': 'Taïwan',
    'hsinchu': 'Taïwan',
    'valladolid': 'Espagne',
    'cidade da praia': 'Cap-Vert',
    'muscat': 'Oman',
    'beirut': 'Liban',
    'manama': 'Bahreïn',
    'baghdad': 'Irak',
    'viseu': 'Portugal',
    'st. gallen': 'Suisse',
    'saint-gall': 'Suisse',
    'zug': 'Suisse',
    'luzern': 'Suisse',
    'lucerne': 'Suisse',
    'phnom penh': 'Cambodge',
    'las palmas de gran canaria': 'Espagne',
    'las palmas': 'Espagne',
    'brno': 'République Tchèque',
    'durban': 'Afrique du Sud',
    'sint-denijs-westrem': 'Belgique',
    'lublin': 'Pologne',
    'baku': 'Azerbaïdjan',
    'tbilisi': 'Géorgie',
    'yerevan': 'Arménie',
    'tashkent': 'Ouzbékistan',
    'almaty': 'Kazakhstan',
    'nairobi': 'Kenya',
    'kampala': 'Ouganda',
    'dar es salaam': 'Tanzanie',
    'gaborone': 'Botswana',
    'windhoek': 'Namibie',
    'asuncion': 'Paraguay',
    'san salvador': 'El Salvador',
    'guatemala city': 'Guatemala',
    'pristina': 'Kosovo',
    'podgorica': 'Monténégro',
    'sarajevo': 'Bosnie-Herzégovine',
    'skopje': 'Macédoine du Nord',
    'tirana': 'Albanie',
    'guayaquil': 'Équateur',
    'ciudad de méxico': 'Mexique',
}


def get_country_from_city(city):
    """
    Retourne le pays pour une ville connue (France, Tunisie, etc.).
    Retourne None si la ville est inconnue.
    """
    if not city or not isinstance(city, str):
        return None
    key = city.strip().lower()
    return CITY_TO_COUNTRY.get(key)


COUNTRY_MAPPING = {
    # Codes ISO 3166-1 alpha-2 → Français (SmartRecruiters, Workday, Oracle HCM…)
    'au': 'Australie',
    'gb': 'Royaume-Uni',
    'de': 'Allemagne',
    'fr': 'France',
    'us': 'États-Unis',
    'ca': 'Canada',
    'be': 'Belgique',
    'ch': 'Suisse',
    'lu': 'Luxembourg',
    'nl': 'Pays-Bas',
    'es': 'Espagne',
    'it': 'Italie',
    'pt': 'Portugal',
    'ie': 'Irlande',
    'at': 'Autriche',
    'pl': 'Pologne',
    'ro': 'Roumanie',
    'hu': 'Hongrie',
    'cz': 'Tchéquie',
    'sk': 'Slovaquie',
    'gr': 'Grèce',
    'dk': 'Danemark',
    'se': 'Suède',
    'no': 'Norvège',
    'fi': 'Finlande',
    'ru': 'Russie',
    'tr': 'Turquie',
    'mc': 'Monaco',
    'gg': 'Guernesey',
    'je': 'Jersey',
    'ua': 'Ukraine',
    'bg': 'Bulgarie',
    'hr': 'Croatie',
    'si': 'Slovénie',
    'lt': 'Lituanie',
    'lv': 'Lettonie',
    'ee': 'Estonie',
    'cy': 'Chypre',
    'mt': 'Malte',
    # Afrique / Moyen-Orient
    'ma': 'Maroc',
    'tn': 'Tunisie',
    'dz': 'Algérie',
    'eg': 'Égypte',
    'sn': 'Sénégal',
    'ci': "Côte d'Ivoire",
    'cm': 'Cameroun',
    'ga': 'Gabon',
    'ng': 'Nigeria',
    'gh': 'Ghana',
    'za': 'Afrique du Sud',
    'dj': 'Djibouti',
    'ke': 'Kenya',
    'cd': 'République Démocratique du Congo',
    'bj': 'Bénin',
    'ml': 'Mali',
    'ne': 'Niger',
    'bf': 'Burkina Faso',
    'tg': 'Togo',
    'ae': 'Émirats Arabes Unis',
    'qa': 'Qatar',
    'sa': 'Arabie Saoudite',
    'il': 'Israël',
    'kw': 'Koweït',
    'bh': 'Bahreïn',
    # Asie / Pacifique
    'in': 'Inde',
    'cn': 'Chine',
    'jp': 'Japon',
    'kr': 'Corée du Sud',
    'sg': 'Singapour',
    'hk': 'Hong-Kong',
    'tw': 'Taïwan',
    'th': 'Thaïlande',
    'vn': 'Vietnam',
    'my': 'Malaisie',
    'id': 'Indonésie',
    'ph': 'Philippines',
    'la': 'Laos',
    'nz': 'Nouvelle-Zélande',
    'nc': 'Nouvelle-Calédonie',
    'pf': 'Polynésie Française',
    'vu': 'Vanuatu',
    # Amériques
    'br': 'Brésil',
    'ar': 'Argentine',
    'cl': 'Chili',
    'mx': 'Mexique',
    'co': 'Colombie',
    'pe': 'Pérou',
    'pa': 'Panama',
    'bs': 'Bahamas',

    # Anglais → Français
    'united states': 'États-Unis',
    'united states of america': 'États-Unis',
    'usa': 'États-Unis',
    'united kingdom': 'Royaume-Uni',
    'uk': 'Royaume-Uni',
    'germany': 'Allemagne',
    'spain': 'Espagne',
    'italy': 'Italie',
    'netherlands': 'Pays-Bas',
    'belgium': 'Belgique',
    'switzerland': 'Suisse',
    'austria': 'Autriche',
    'poland': 'Pologne',
    'czech republic': 'Tchéquie',
    'czechia': 'Tchéquie',
    'romania': 'Roumanie',
    'hungary': 'Hongrie',
    'portugal': 'Portugal',
    'greece': 'Grèce',
    'denmark': 'Danemark',
    'sweden': 'Suède',
    'norway': 'Norvège',
    'finland': 'Finlande',
    'ireland': 'Irlande',
    'russia': 'Russie',
    'turkey': 'Turquie',
    
    # Asie / Océanie
    'india': 'Inde',
    'china': 'Chine',
    'japan': 'Japon',
    'south korea': 'Corée du Sud',
    'korea': 'Corée du Sud',
    'taiwan': 'Taïwan',
    'taïwan': 'Taïwan',
    'singapore': 'Singapour',
    'malaysia': 'Malaisie',
    'vietnam': 'Vietnam',
    'thailand': 'Thaïlande',
    'australia': 'Australie',
    'new zealand': 'Nouvelle-Zélande',
    'new caledonia': 'Nouvelle-Calédonie',
    'nouvelle caledonie': 'Nouvelle-Calédonie',
    'nouvelle-caledonie': 'Nouvelle-Calédonie',
    'polynésie française': 'Polynésie Française',
    'polynesie francaise': 'Polynésie Française',
    'french polynesia': 'Polynésie Française',
    'vanuatu': 'Vanuatu',
    'philippines': 'Philippines',
    'bahrain': 'Bahreïn',
    'bahreïn': 'Bahreïn',
    'israel': 'Israël',
    'peru': 'Pérou',
    'pérou': 'Pérou',
    'laos': 'Laos',
    'nigeria': 'Nigeria',
    'kenya': 'Kenya',
    
    # Afrique / Moyen-Orient
    'morocco': 'Maroc',
    'tunisia': 'Tunisie',
    'algeria': 'Algérie',
    'djibouti': 'Djibouti',
    'indonesia': 'Indonésie',
    'egypt': 'Égypte',
    'south africa': 'Afrique du Sud',
    'afrique du sud': 'Afrique du Sud',
    'afrique du sud (remote)': 'Afrique du Sud',
    'tunisie': 'Tunisie',
    'koweït': 'Koweït',
    'koweit': 'Koweït',
    'united arab emirates': 'Émirats Arabes Unis',
    'uae': 'Émirats Arabes Unis',
    'dubai': 'Émirats Arabes Unis',
    'qatar': 'Qatar',
    'saudi arabia': 'Arabie Saoudite',
    
    # Amériques
    'brazil': 'Brésil',
    'argentina': 'Argentine',
    'chile': 'Chili',
    'mexico': 'Mexique',
    'colombia': 'Colombie',
    'canada': 'Canada',
    
    # Europe (Français / Stable)
    'france': 'France',
    'luxembourg': 'Luxembourg',
    'monaco': 'Monaco',
    'belgique': 'Belgique',
    'suisse': 'Suisse',
    'italie': 'Italie',
    'espagne': 'Espagne',
    'allemagne': 'Allemagne',
    'guernsey': 'Guernesey',
    'guernesey': 'Guernesey',
    'tchéquie': 'Tchéquie',
    'tchequie': 'Tchéquie',
    'république tchèque': 'Tchéquie',
    'republique tcheque': 'Tchéquie',
    'indonésie': 'Indonésie',
    'indonesie': 'Indonésie',
    'hong-kong': 'Hong-Kong',
    'hong kong': 'Hong-Kong',
    'corée du sud': 'Corée du Sud',
    'corée Du Sud': 'Corée du Sud',
    'algerie': 'Algérie',
    'algérie': 'Algérie',
    'algeria': 'Algérie',
    'deutschlandweit': 'Allemagne',
    'millénaire 4': 'France',
    'millenaire 4': 'France',
    # Noms complets FR supplémentaires (normalisation casse/accents)
    'république démocratique du congo': 'République Démocratique du Congo',
    'republique democratique du congo': 'République Démocratique du Congo',
    'rd congo': 'République Démocratique du Congo',
    'congo (rdc)': 'République Démocratique du Congo',
    'ukraine': 'Ukraine',
    'jersey': 'Jersey',
    'sénégal': 'Sénégal',
    'senegal': 'Sénégal',
    'côte d\'ivoire': "Côte d'Ivoire",
    "cote d'ivoire": "Côte d'Ivoire",
    'bénin': 'Bénin',
    'benin': 'Bénin',
    'burkina faso': 'Burkina Faso',
    'bahreïn': 'Bahreïn',
    'bahrain': 'Bahreïn',
    'koweït': 'Koweït',
    'kuwait': 'Koweït',
    'croatie': 'Croatie',
    'croatia': 'Croatie',
    'slovaquie': 'Slovaquie',
    'slovakia': 'Slovaquie',
    'slovénie': 'Slovénie',
    'slovenia': 'Slovénie',
    'bulgarie': 'Bulgarie',
    'bulgaria': 'Bulgarie',
    'lituanie': 'Lituanie',
    'lithuania': 'Lituanie',
    'lettonie': 'Lettonie',
    'latvia': 'Lettonie',
    'estonie': 'Estonie',
    'estonia': 'Estonie',
    'chypre': 'Chypre',
    'cyprus': 'Chypre',
}

def normalize_country(country_raw):
    """
    Normalise le nom d'un pays en français
    """
    if not country_raw:
        return country_raw
    
    country_clean = country_raw.strip()
    
    # Supprimer le préfixe "- " si présent (ex: "- France" → "France")
    if country_clean.startswith('- '):
        country_clean = country_clean[2:].strip()
    
    country_clean = country_clean.lower()
    
    # Supprimer les codes numériques (ex: "91" qui est un département français)
    if country_clean.isdigit() or (len(country_clean) <= 3 and country_clean.isdigit()):
        return "France"  # Les codes numériques courts sont probablement des départements français
    
    # Cas particuliers avant découpe sur virgule
    # Ex: \"Korea, Republic Of\" → Corée du Sud
    if 'korea' in country_clean:
        return 'Corée du Sud'
    if country_clean == 'republic of':
        return 'Corée du Sud'
    # Villes qui ne sont pas des pays (ex: Grandcamp Maisy) → France
    if country_clean == 'grandcamp maisy':
        return 'France'
    
    # Supprimer les codes ISO ou régions si présents après une virgule
    if ',' in country_clean:
        country_clean = country_clean.split(',')[-1].strip()
    
    # Normaliser les variantes courantes
    country_variants = {
        'etats-unis': 'États-Unis',
        'etats unis': 'États-Unis',
        'etats-unis d\'amérique': 'États-Unis',
        'etats unis d\'amérique': 'États-Unis',
        'usa': 'États-Unis',
        'u.s.a': 'États-Unis',
        'corée': 'Corée du Sud',
        'corée du sud': 'Corée du Sud',
        'viet nam': 'Vietnam',
        'vietnam': 'Vietnam',
        'turkiye': 'Turquie',
        'türkiye': 'Turquie',
        'israel': 'Israël',
        'bahamas': 'Bahamas',
        'panama': 'Panama',
        'laos': 'Laos',
        'kuwait': 'Koweït',
        'peru': 'Pérou',
        'qatar': 'Qatar',
    }
    
    # Vérifier les variantes d'abord
    if country_clean in country_variants:
        return country_variants[country_clean]
        
    if country_clean in COUNTRY_MAPPING:
        return COUNTRY_MAPPING[country_clean]
    
    # Si pas dans le mapping, mettre la première lettre en majuscule
    result = country_raw.strip()
    if result.startswith('- '):
        result = result[2:].strip()
    result = result.title()
    
    # Harmoniser "France" (toujours retourner "France" sans préfixe)
    if result.lower() == 'france' or result == '- France':
        return 'France'
    
    return result
